In [1]:
import open3d as o3d
import numpy as np


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
print("Load a ply point cloud, print it, and render it")
# ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.io.read_point_cloud('D:\Project\AMRITA PROJECTS\Fall Detection\Lidar ply\Sitting .ply')
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

Load a ply point cloud, print it, and render it
PointCloud with 7936 points.
[[-0.19305584 -0.21078862 -1.31585312]
 [-0.22136071 -0.21485668 -1.31774437]
 [-0.19462633 -0.22975907 -1.31143022]
 ...
 [ 0.6668703  -0.49231035 -0.93051416]
 [ 0.68054211 -0.48815751 -0.9308871 ]
 [ 0.75817811 -0.48951572 -1.18738639]]


In [3]:
print("Downsample the point cloud with a voxel of 0.05")
downpcd = pcd.voxel_down_sample(voxel_size=0.05)
o3d.visualization.draw_geometries([downpcd])

Downsample the point cloud with a voxel of 0.05
